services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nest-api
      - JWT_SECRET=seuSegredoAqui
      - SENTRY_DSN=https://<sua-dsn-do-sentry>
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
